In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.datasets import make_blobs
from matplotlib.widgets import Slider
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [2]:
def my_softmax(x):
    ez=np.exp(x)
    sm = ez/np.sum(ez)
    return sm

In [4]:
centers = [[-5,2],[-2,-2],[1,2],[5,-2]]
xTrain,yTrain = make_blobs(n_samples=2000,centers=centers,cluster_std=1,random_state=30)

In [5]:
model = Sequential(
    [
        Dense(25,activation='relu'),
        Dense(15,activation='relu'),
        Dense(4,activation='softmax')
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
)
model.fit(
    xTrain,yTrain,epochs=10
)

Epoch 1/10
63/63 [==============================] - 2s 3ms/step - loss: 1.3486
Epoch 2/10
63/63 [==============================] - 0s 1ms/step - loss: 0.6244
Epoch 3/10
63/63 [==============================] - 0s 1ms/step - loss: 0.3752
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.2320
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1388
Epoch 6/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0890
Epoch 7/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0688
Epoch 8/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0582
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0512
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0467


In [7]:
pNonPreffered = model.predict(xTrain)
print(pNonPreffered[:2])
print(f'largest value {np.max(pNonPreffered)},smallest value {np.min(pNonPreffered)}')

63/63 [==============================] - 0s 832us/step
[[9.6940147e-03 1.5809899e-03 9.4250631e-01 4.6218589e-02]
 [9.9391067e-01 5.8769300e-03 5.0514602e-05 1.6187673e-04]]
largest value 0.9999996423721313,smallest value 2.2103401053907845e-10


In [9]:
prefferedModel = Sequential(
    [
        Dense(25,activation='relu'),
        Dense(15,activation='relu'),
        Dense(4,activation='softmax')
    ]
)
prefferedModel.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
)
prefferedModel.fit(
    xTrain,yTrain,epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 1ms/step - loss: 1.2285
Epoch 2/10
63/63 [==============================] - 0s 1ms/step - loss: 0.5513
Epoch 3/10
63/63 [==============================] - 0s 1ms/step - loss: 0.2358
Epoch 4/10
63/63 [==============================] - 0s 1ms/step - loss: 0.1275
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0875
Epoch 6/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0690
Epoch 7/10
63/63 [==============================] - 0s 3ms/step - loss: 0.0584
Epoch 8/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0518
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0473
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0438


In [10]:
pPreffered = model.predict(xTrain)
print(pPreffered[:2])
print(f'largest value {np.max(pPreffered)},smallest value {np.min(pPreffered)}')

63/63 [==============================] - 0s 1ms/step
[[9.6940147e-03 1.5809899e-03 9.4250631e-01 4.6218589e-02]
 [9.9391067e-01 5.8769300e-03 5.0514602e-05 1.6187673e-04]]
largest value 0.9999996423721313,smallest value 2.2103401053907845e-10


In [11]:
smPreffered = tf.nn.softmax(pPreffered).numpy()
print(f"two example output vectors:\n {smPreffered[:2]}")
print("largest value", np.max(smPreffered), "smallest value", np.min(smPreffered))

two example output vectors:
 [[0.1795085  0.17805806 0.45624727 0.1861862 ]
 [0.47334155 0.17622887 0.17520507 0.17522457]]
largest value 0.47536677 smallest value 0.17487772


In [12]:
for i in range(5):
    print( f"{pPreffered[i]}, category: {np.argmax(pPreffered[i])}")

[0.00969401 0.00158099 0.9425063  0.04621859], category: 2
[9.9391067e-01 5.8769300e-03 5.0514602e-05 1.6187673e-04], category: 0
[9.5700926e-01 4.1242633e-02 6.2452466e-04 1.1235843e-03], category: 0
[0.00781677 0.9877664  0.00246671 0.00195024], category: 1
[0.0092671  0.00105116 0.9880242  0.00165752], category: 2
